name: Build and deploy Python app to Azure Web App - hiramatsutest2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # GitHubリポジトリからコードを取得
    - uses: actions/checkout@v2

    # Python 3.8をセットアップ
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    # 必要なパッケージをインストール
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Azure Web Appにデプロイ
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'hiramatsutest2'  # Azure Web Appの名前を指定
        slot-name: 'production'     # スロットがない場合は 'production' を指定
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
